### ISSUE TITLE
Current Geo Location

### ISSUE THREAD

**Issue by aouniradouan** [wwwouaiebe/TravelNotes#43]
Hi sir, Thank you for this great project
i want to ask if is there a way to add Current Geo Location for the user and track it in the real time with the coordinates and send the informations to db via ajax with some extra features like geo location live pictures and name ?

**Comment by wwwouaiebe** [comment]
First see the GeoLocator class in the src/core/GeoLocator.js file and the mdn documentattion on GeoLocation interface.
As you can see, the GeoLocator class uses already the getCurrentPosition ( ) and watchPosition ( ) methods of the GeoLocation interface and the current position can be saved and send to a db with a modification of the GeoLocator.#showPosition ( ) method.
But I see at least two problems with this:
- the watchPosition ( ) method don't work correctly with some browsers (Firefox for Androïd , perhaps Brave with AndroÏd) and currently I cannot say where is exactly the problem (Firefox, Brave or Androïd?)
- the second problem is legal: remember that, at least in the EU, we have to respect the GDPR (General Data Protection Regulation) and we cannot register the position of a user without having the agrement of this user.

And also some remarks about the accuracy of the getCurrentPosition ( ):
- when the wifi is enabled on the device the accuracy is frequently very good (getCurrentPosition ( ) call a function in a Google data center and this function returns the position based on the wifi position that was found when a Google car was passing near the wifi (and notice also that using this function you give your position to Google...)
- but when the wifi is not enabled or no wifi near your device or no Google car was passed near your position, the accuracy can be bad, because the getCurrentPosition ( ) try to find your position from the GSM antennas. Last month I go to nord of Sweden, in some places whithout wifi and great distances between GSM antennas and the accuracy was very bad, betwwen 800 m and more than 20 km.
- I have also made some test from my home with or without wifi enabled on my device. With wifi enabled the accurracy is very good (+/- 20 m), but wihout wifi, I have the same problem : accuracy is between 800 m and 5 km (and can be different each time the getCurrentPosition ( ) is called.
